/**
 * dsh-ko-locale — browser half.
 *
 * Registers Korean as a selectable DSH locale and serves Korean copy for every
 * namespace the shipped client plugins register.
 *
 * Why this patches the locale runtime instead of only calling
 * `ctx.locale.register(ns, 'ko', {...})`:
 *
 *   `LocaleRuntime.register` rejects a namespace/locale pair that is already
 *   registered (`locale namespace "<ns>" already has locale "ko"`), and it has
 *   no replace/merge entry point. A language pack therefore cannot take over a
 *   built-in namespace through the public dictionary API. `lookup` is the one
 *   seam every translation read funnels through (`bind` -> `translate` ->
 *   `lookup`), so overriding it on `LocaleRuntime.prototype` reaches all copy
 *   without touching any package's registration.
 *
 * The pack only overrides where it has an entry; everything else falls through
 * to the built-in English dictionary unchanged, so a partial pack degrades to
 * English per key rather than to a raw key name.
 *
 * Entry point shape (see @deepseek-ai/dsh-client-modules): the loader calls
 * `factory(require)`, executing it registers a factory only, and the module
 * body runs at materialization. `exports.apply` / `exports.inject` are the
 * cordis client-plugin contract.
 */
window.__ModuleLoader__.load({
  id: 'dsh-ko-locale',
  factory: (require) => {
    var module = { exports: {} }
    var exports = module.exports

    /**
     * Korean dictionary overlay: namespace -> { key -> Korean }.
     * Generated by tools/build.mjs from data/ko.json — edit that file and
     * rerun the build, never this literal.
     */
    const DICTIONARIES = /*__KO_DICTIONARIES__*/ {}

    /** Locale id this pack installs. */
    const KOREAN = 'ko'
    /** Label shown in Settings -> General -> Language. */
    const KOREAN_LABEL = '한국어'
    /** Terminal fallback every DSH language chain must reach. */
    const ENGLISH = 'en'
    /** Marks a prototype this pack already patched. */
    const PATCH_MARK = '__dshKoLocalePatched__'

    /** Total keys the pack carries, for the status surface. */
    const KEY_COUNT = Object.keys(DICTIONARIES).reduce((sum, ns) => sum + Object.keys(DICTIONARIES[ns]).length, 0)

    /**
     * Whether the host machine asks for Korean. The native desktop shell
     * supplies its own ordered OS languages through `__DSH_LOCALE__`; the
     * `navigator` fallback covers ordinary browsers.
     * @returns true when any requested tag is Korean.
     */
    function machineWantsKorean() {
      if (typeof navigator === 'undefined') return false
      const tags = [...(navigator.languages ?? []), navigator.language]
      return tags.some((tag) => typeof tag === 'string' && tag.toLowerCase().split('-')[0] === KOREAN)
    }

    /**
     * Whether an explicit locale choice is already stored. A stored choice is
     * always honoured; only a fresh profile takes Korean from the machine.
     * @param runtime - the locale runtime instance.
     * @returns true when the durable preference names a language.
     */
    function hasStoredPreference(runtime) {
      try {
        const section = runtime.host?.getSnapshot?.().value
        return typeof section?.preference === 'string' && section.preference !== ''
      } catch {
        return false
      }
    }

    /**
     * Walk the instance's prototype chain to the class that owns the locale
     * internals. `LocaleRuntime` is not exported from the package's `./client`
     * entry, so the class is identified structurally instead of by import.
     * @param runtime - the locale runtime instance.
     * @returns the owning prototype, or undefined when the shape is unknown.
     */
    function findLocalePrototype(runtime) {
      let proto = Object.getPrototypeOf(runtime)
      while (proto !== null && proto !== Object.prototype) {
        if (
          typeof proto.lookup === 'function' &&
          typeof proto.register === 'function' &&
          typeof proto.addLanguage === 'function' &&
          typeof proto.resolveActive === 'function'
        ) {
          return proto
        }
        proto = Object.getPrototypeOf(proto)
      }
      return undefined
    }

    /**
     * Install the Korean overlay on the locale runtime.
     * @param runtime - the locale runtime instance provided as `ctx.locale`.
     * @returns a disposer restoring the runtime's original behavior.
     */
    function patchLocaleRuntime(runtime) {
      const proto = findLocalePrototype(runtime)
      if (proto === undefined) {
        console.error('dsh-ko-locale: unrecognized locale runtime; Korean copy was not installed')
        return () => {}
      }
      if (Object.prototype.hasOwnProperty.call(proto, PATCH_MARK)) return () => {}

      const originalLookup = proto.lookup
      const originalResolveActive = proto.resolveActive
      const originalLocaleList = proto.localeList
      const originalPublish = proto.publish
      const originalRegister = proto.register

      /**
       * Namespaces another plugin already localized into Korean. Such an owner
       * outranks this pack, so its entries are served unchanged.
       */
      const reserved = new Set()

      proto.register = function (ns, localeOrDicts, dict) {
        const locales = typeof localeOrDicts === 'string' ? [localeOrDicts] : Object.keys(localeOrDicts)
        if (locales.some((locale) => String(locale).toLowerCase() === KOREAN)) reserved.add(String(ns))
        return originalRegister.call(this, ns, localeOrDicts, dict)
      }

      /** This pack's entries for a namespace, or undefined when it has none. */
      function entriesFor(ns) {
        return reserved.has(ns) ? undefined : DICTIONARIES[ns]
      }

      /** Active-locale memo, invalidated by every publish. */
      let koreanActive

      function servesKorean() {
        if (koreanActive === undefined) {
          try {
            koreanActive = this.snapshot.active === KOREAN
          } catch {
            koreanActive = false
          }
        }
        return koreanActive
      }

      /* Every translation read passes through lookup, so one override reaches
       * `bind`-produced translators, the framework `t` seat, and slot copy. */
      proto.lookup = function (ns, key, chain) {
        if (servesKorean.call(this)) {
          const entries = entriesFor(ns)
          const value = entries === undefined ? undefined : entries[key]
          if (value !== undefined) return value
        }
        return originalLookup.call(this, ns, key, chain)
      }

      /** Whether a locale list already carries Korean. */
      function carriesKorean(locales) {
        return locales.some((locale) => String(locale.id).toLowerCase() === KOREAN)
      }

      /* `addLanguage` publishes through `publishCatalog` -> `localeList` ->
       * `resolveActive`, and both read `this.snapshot`, which still describes
       * the pre-registration world. They therefore read the catalog directly:
       * once a locale is in the catalog it must never be reported as absent. */
      proto.localeList = function () {
        const locales = originalLocaleList.call(this)
        if (carriesKorean(locales)) return locales
        const korean = this.catalog?.get(KOREAN)
        return korean === undefined ? locales : Object.freeze([...locales, korean])
      }

      /* The provisional locale is computed in the constructor, before any
       * language pack can register, so a Korean machine would otherwise open
       * in English. Re-decide while no explicit choice is stored. */
      proto.resolveActive = function () {
        const active = originalResolveActive.call(this)
        if (active === KOREAN) return active
        if (hasStoredPreference(this)) return active
        if (this.catalog?.has(KOREAN) !== true) return active
        return machineWantsKorean() ? KOREAN : active
      }

      proto.publish = function (...rest) {
        koreanActive = undefined
        return originalPublish.apply(this, rest)
      }

      try {
        Object.defineProperty(proto, PATCH_MARK, { value: true, configurable: true })
      } catch {
        /* A frozen prototype still supports the overrides above. */
      }

      return () => {
        proto.publish = originalPublish
        proto.resolveActive = originalResolveActive
        proto.localeList = originalLocaleList
        proto.lookup = originalLookup
        proto.register = originalRegister
        try {
          delete proto[PATCH_MARK]
        } catch {
          /* Non-configurable marker; the overrides are restored regardless. */
        }
      }
    }

    /**
     * Register Korean in the locale catalog and install the overlay.
     * @param ctx - the client plugin context.
     * @returns a disposer removing both contributions.
     */
    function installKoreanLocale(ctx) {
      const runtime = ctx.locale
      if (runtime === undefined || runtime === null) return () => {}
      const restorePatch = patchLocaleRuntime(runtime)

      /* Registering the language after the patch matters: `publishCatalog`
       * runs inside `addLanguage` and must already see the overlay. */
      let removeLanguage = () => {}
      try {
        removeLanguage =
          runtime.addLanguage({ id: KOREAN, label: KOREAN_LABEL, fallback: ENGLISH }) ?? (() => {})
      } catch (error) {
        console.error('dsh-ko-locale: could not register the Korean language', error)
      }

      return () => {
        try {
          removeLanguage()
        } catch {
          /* Already disposed by the runtime. */
        }
        restorePatch()
      }
    }

    /** Required service: the locale registry this pack extends. */
    const inject = ['locale']

    /**
     * Client plugin body.
     * @param ctx - client cordis context.
     */
    function apply(ctx) {
      ctx.effect(() => installKoreanLocale(ctx), 'dsh-ko-locale: Korean language pack')
      globalThis.__DSH_KO_LOCALE__ = Object.freeze({
        locale: KOREAN,
        namespaces: Object.keys(DICTIONARIES).length,
        keys: KEY_COUNT,
      })
    }

    exports.apply = apply
    exports.inject = inject
    exports.KOREAN_LOCALE_ID = KOREAN
    exports.DICTIONARIES = DICTIONARIES

    return module.exports
  },
})
